// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.iflytek.ctr.person.proto

package com.protobf;

public final class ComIflytekCtrPerson {
  private ComIflytekCtrPerson() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 acctID = 1;
    /**
     * <code>required int64 acctID = 1;</code>
     */
    boolean hasAcctID();
    /**
     * <code>required int64 acctID = 1;</code>
     */
    long getAcctID();

    // required string passwd = 2;
    /**
     * <code>required string passwd = 2;</code>
     */
    boolean hasPasswd();
    /**
     * <code>required string passwd = 2;</code>
     */
    String getPasswd();
    /**
     * <code>required string passwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();

    // repeated int64 index = 3;
    /**
     * <code>repeated int64 index = 3;</code>
     */
    java.util.List<Long> getIndexList();
    /**
     * <code>repeated int64 index = 3;</code>
     */
    int getIndexCount();
    /**
     * <code>repeated int64 index = 3;</code>
     */
    long getIndex(int index);

    // repeated int64 value = 4;
    /**
     * <code>repeated int64 value = 4;</code>
     */
    java.util.List<Long> getValueList();
    /**
     * <code>repeated int64 value = 4;</code>
     */
    int getValueCount();
    /**
     * <code>repeated int64 value = 4;</code>
     */
    long getValue(int index);

    // repeated .com.protobf.App apps = 5;
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    java.util.List<App>
        getAppsList();
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    App getApps(int index);
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    int getAppsCount();
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    java.util.List<? extends AppOrBuilder>
        getAppsOrBuilderList();
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    AppOrBuilder getAppsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.protobf.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              acctID_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              passwd_ = input.readBytes();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                index_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              index_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                index_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                index_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                value_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              value_.add(input.readInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                value_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                value_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                apps_ = new java.util.ArrayList<App>();
                mutable_bitField0_ |= 0x00000010;
              }
              apps_.add(input.readMessage(App.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          index_ = java.util.Collections.unmodifiableList(index_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          value_ = java.util.Collections.unmodifiableList(value_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          apps_ = java.util.Collections.unmodifiableList(apps_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ComIflytekCtrPerson.internal_static_com_protobf_Person_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ComIflytekCtrPerson.internal_static_com_protobf_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 acctID = 1;
    public static final int ACCTID_FIELD_NUMBER = 1;
    private long acctID_;
    /**
     * <code>required int64 acctID = 1;</code>
     */
    public boolean hasAcctID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 acctID = 1;</code>
     */
    public long getAcctID() {
      return acctID_;
    }

    // required string passwd = 2;
    public static final int PASSWD_FIELD_NUMBER = 2;
    private Object passwd_;
    /**
     * <code>required string passwd = 2;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string passwd = 2;</code>
     */
    public String getPasswd() {
      Object ref = passwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string passwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      Object ref = passwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated int64 index = 3;
    public static final int INDEX_FIELD_NUMBER = 3;
    private java.util.List<Long> index_;
    /**
     * <code>repeated int64 index = 3;</code>
     */
    public java.util.List<Long>
        getIndexList() {
      return index_;
    }
    /**
     * <code>repeated int64 index = 3;</code>
     */
    public int getIndexCount() {
      return index_.size();
    }
    /**
     * <code>repeated int64 index = 3;</code>
     */
    public long getIndex(int index) {
      return index_.get(index);
    }

    // repeated int64 value = 4;
    public static final int VALUE_FIELD_NUMBER = 4;
    private java.util.List<Long> value_;
    /**
     * <code>repeated int64 value = 4;</code>
     */
    public java.util.List<Long>
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated int64 value = 4;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated int64 value = 4;</code>
     */
    public long getValue(int index) {
      return value_.get(index);
    }

    // repeated .com.protobf.App apps = 5;
    public static final int APPS_FIELD_NUMBER = 5;
    private java.util.List<App> apps_;
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    public java.util.List<App> getAppsList() {
      return apps_;
    }
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    public java.util.List<? extends AppOrBuilder>
        getAppsOrBuilderList() {
      return apps_;
    }
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    public int getAppsCount() {
      return apps_.size();
    }
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    public App getApps(int index) {
      return apps_.get(index);
    }
    /**
     * <code>repeated .com.protobf.App apps = 5;</code>
     */
    public AppOrBuilder getAppsOrBuilder(
        int index) {
      return apps_.get(index);
    }

    private void initFields() {
      acctID_ = 0L;
      passwd_ = "";
      index_ = java.util.Collections.emptyList();
      value_ = java.util.Collections.emptyList();
      apps_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAcctID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPasswd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAppsCount(); i++) {
        if (!getApps(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, acctID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswdBytes());
      }
      for (int i = 0; i < index_.size(); i++) {
        output.writeInt64(3, index_.get(i));
      }
      for (int i = 0; i < value_.size(); i++) {
        output.writeInt64(4, value_.get(i));
      }
      for (int i = 0; i < apps_.size(); i++) {
        output.writeMessage(5, apps_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, acctID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < index_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(index_.get(i));
        }
        size += dataSize;
        size += 1 * getIndexList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(value_.get(i));
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      for (int i = 0; i < apps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, apps_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobf.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ComIflytekCtrPerson.internal_static_com_protobf_Person_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ComIflytekCtrPerson.internal_static_com_protobf_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.class, Builder.class);
      }

      // Construct using com.protobf.ComIflytekCtrPerson.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        acctID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        index_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        if (appsBuilder_ == null) {
          apps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          appsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ComIflytekCtrPerson.internal_static_com_protobf_Person_descriptor;
      }

      public Person getDefaultInstanceForType() {
        return Person.getDefaultInstance();
      }

      public Person build() {
        Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person buildPartial() {
        Person result = new Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.acctID_ = acctID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passwd_ = passwd_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          index_ = java.util.Collections.unmodifiableList(index_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.index_ = index_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.value_ = value_;
        if (appsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            apps_ = java.util.Collections.unmodifiableList(apps_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.apps_ = apps_;
        } else {
          result.apps_ = appsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person) {
          return mergeFrom((Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person other) {
        if (other == Person.getDefaultInstance()) return this;
        if (other.hasAcctID()) {
          setAcctID(other.getAcctID());
        }
        if (other.hasPasswd()) {
          bitField0_ |= 0x00000002;
          passwd_ = other.passwd_;
          onChanged();
        }
        if (!other.index_.isEmpty()) {
          if (index_.isEmpty()) {
            index_ = other.index_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIndexIsMutable();
            index_.addAll(other.index_);
          }
          onChanged();
        }
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        if (appsBuilder_ == null) {
          if (!other.apps_.isEmpty()) {
            if (apps_.isEmpty()) {
              apps_ = other.apps_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAppsIsMutable();
              apps_.addAll(other.apps_);
            }
            onChanged();
          }
        } else {
          if (!other.apps_.isEmpty()) {
            if (appsBuilder_.isEmpty()) {
              appsBuilder_.dispose();
              appsBuilder_ = null;
              apps_ = other.apps_;
              bitField0_ = (bitField0_ & ~0x00000010);
              appsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAppsFieldBuilder() : null;
            } else {
              appsBuilder_.addAllMessages(other.apps_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAcctID()) {
          
          return false;
        }
        if (!hasPasswd()) {
          
          return false;
        }
        for (int i = 0; i < getAppsCount(); i++) {
          if (!getApps(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 acctID = 1;
      private long acctID_ ;
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public boolean hasAcctID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public long getAcctID() {
        return acctID_;
      }
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public Builder setAcctID(long value) {
        bitField0_ |= 0x00000001;
        acctID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public Builder clearAcctID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        acctID_ = 0L;
        onChanged();
        return this;
      }

      // required string passwd = 2;
      private Object passwd_ = "";
      /**
       * <code>required string passwd = 2;</code>
       */
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public String getPasswd() {
        Object ref = passwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          passwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        Object ref = passwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public Builder setPasswd(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passwd_ = getDefaultInstance().getPasswd();
        onChanged();
        return this;
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        onChanged();
        return this;
      }

      // repeated int64 index = 3;
      private java.util.List<Long> index_ = java.util.Collections.emptyList();
      private void ensureIndexIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          index_ = new java.util.ArrayList<Long>(index_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 index = 3;</code>
       */
      public java.util.List<Long>
          getIndexList() {
        return java.util.Collections.unmodifiableList(index_);
      }
      /**
       * <code>repeated int64 index = 3;</code>
       */
      public int getIndexCount() {
        return index_.size();
      }
      /**
       * <code>repeated int64 index = 3;</code>
       */
      public long getIndex(int index) {
        return index_.get(index);
      }
      /**
       * <code>repeated int64 index = 3;</code>
       */
      public Builder setIndex(
          int index, long value) {
        ensureIndexIsMutable();
        index_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 index = 3;</code>
       */
      public Builder addIndex(long value) {
        ensureIndexIsMutable();
        index_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 index = 3;</code>
       */
      public Builder addAllIndex(
          Iterable<? extends Long> values) {
        ensureIndexIsMutable();
        super.addAll(values, index_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 index = 3;</code>
       */
      public Builder clearIndex() {
        index_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // repeated int64 value = 4;
      private java.util.List<Long> value_ = java.util.Collections.emptyList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          value_ = new java.util.ArrayList<Long>(value_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int64 value = 4;</code>
       */
      public java.util.List<Long>
          getValueList() {
        return java.util.Collections.unmodifiableList(value_);
      }
      /**
       * <code>repeated int64 value = 4;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated int64 value = 4;</code>
       */
      public long getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated int64 value = 4;</code>
       */
      public Builder setValue(
          int index, long value) {
        ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 value = 4;</code>
       */
      public Builder addValue(long value) {
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 value = 4;</code>
       */
      public Builder addAllValue(
          Iterable<? extends Long> values) {
        ensureValueIsMutable();
        super.addAll(values, value_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 value = 4;</code>
       */
      public Builder clearValue() {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated .com.protobf.App apps = 5;
      private java.util.List<App> apps_ =
        java.util.Collections.emptyList();
      private void ensureAppsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          apps_ = new java.util.ArrayList<App>(apps_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          App, App.Builder, AppOrBuilder> appsBuilder_;

      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public java.util.List<App> getAppsList() {
        if (appsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(apps_);
        } else {
          return appsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public int getAppsCount() {
        if (appsBuilder_ == null) {
          return apps_.size();
        } else {
          return appsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public App getApps(int index) {
        if (appsBuilder_ == null) {
          return apps_.get(index);
        } else {
          return appsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder setApps(
          int index, App value) {
        if (appsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppsIsMutable();
          apps_.set(index, value);
          onChanged();
        } else {
          appsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder setApps(
          int index, App.Builder builderForValue) {
        if (appsBuilder_ == null) {
          ensureAppsIsMutable();
          apps_.set(index, builderForValue.build());
          onChanged();
        } else {
          appsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder addApps(App value) {
        if (appsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppsIsMutable();
          apps_.add(value);
          onChanged();
        } else {
          appsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder addApps(
          int index, App value) {
        if (appsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppsIsMutable();
          apps_.add(index, value);
          onChanged();
        } else {
          appsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder addApps(
          App.Builder builderForValue) {
        if (appsBuilder_ == null) {
          ensureAppsIsMutable();
          apps_.add(builderForValue.build());
          onChanged();
        } else {
          appsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder addApps(
          int index, App.Builder builderForValue) {
        if (appsBuilder_ == null) {
          ensureAppsIsMutable();
          apps_.add(index, builderForValue.build());
          onChanged();
        } else {
          appsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder addAllApps(
          Iterable<? extends App> values) {
        if (appsBuilder_ == null) {
          ensureAppsIsMutable();
          super.addAll(values, apps_);
          onChanged();
        } else {
          appsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder clearApps() {
        if (appsBuilder_ == null) {
          apps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          appsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public Builder removeApps(int index) {
        if (appsBuilder_ == null) {
          ensureAppsIsMutable();
          apps_.remove(index);
          onChanged();
        } else {
          appsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public App.Builder getAppsBuilder(
          int index) {
        return getAppsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public AppOrBuilder getAppsOrBuilder(
          int index) {
        if (appsBuilder_ == null) {
          return apps_.get(index);  } else {
          return appsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public java.util.List<? extends AppOrBuilder>
           getAppsOrBuilderList() {
        if (appsBuilder_ != null) {
          return appsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(apps_);
        }
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public App.Builder addAppsBuilder() {
        return getAppsFieldBuilder().addBuilder(
            App.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public App.Builder addAppsBuilder(
          int index) {
        return getAppsFieldBuilder().addBuilder(
            index, App.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protobf.App apps = 5;</code>
       */
      public java.util.List<App.Builder>
           getAppsBuilderList() {
        return getAppsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          App, App.Builder, AppOrBuilder>
          getAppsFieldBuilder() {
        if (appsBuilder_ == null) {
          appsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              App, App.Builder, AppOrBuilder>(
                  apps_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          apps_ = null;
        }
        return appsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.protobf.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protobf.Person)
  }

  public interface AppOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string pkg = 1;
    /**
     * <code>required string pkg = 1;</code>
     */
    boolean hasPkg();
    /**
     * <code>required string pkg = 1;</code>
     */
    String getPkg();
    /**
     * <code>required string pkg = 1;</code>
     */
    com.google.protobuf.ByteString
        getPkgBytes();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 activeDays = 3;
    /**
     * <code>optional int32 activeDays = 3;</code>
     */
    boolean hasActiveDays();
    /**
     * <code>optional int32 activeDays = 3;</code>
     */
    int getActiveDays();

    // optional int32 collectDays = 4;
    /**
     * <code>optional int32 collectDays = 4;</code>
     */
    boolean hasCollectDays();
    /**
     * <code>optional int32 collectDays = 4;</code>
     */
    int getCollectDays();
  }
  /**
   * Protobuf type {@code com.protobf.App}
   */
  public static final class App extends
      com.google.protobuf.GeneratedMessage
      implements AppOrBuilder {
    // Use App.newBuilder() to construct.
    private App(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private App(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final App defaultInstance;
    public static App getDefaultInstance() {
      return defaultInstance;
    }

    public App getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private App(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pkg_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              activeDays_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              collectDays_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ComIflytekCtrPerson.internal_static_com_protobf_App_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ComIflytekCtrPerson.internal_static_com_protobf_App_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              App.class, Builder.class);
    }

    public static com.google.protobuf.Parser<App> PARSER =
        new com.google.protobuf.AbstractParser<App>() {
      public App parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new App(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<App> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string pkg = 1;
    public static final int PKG_FIELD_NUMBER = 1;
    private Object pkg_;
    /**
     * <code>required string pkg = 1;</code>
     */
    public boolean hasPkg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string pkg = 1;</code>
     */
    public String getPkg() {
      Object ref = pkg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pkg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pkg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPkgBytes() {
      Object ref = pkg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pkg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 activeDays = 3;
    public static final int ACTIVEDAYS_FIELD_NUMBER = 3;
    private int activeDays_;
    /**
     * <code>optional int32 activeDays = 3;</code>
     */
    public boolean hasActiveDays() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 activeDays = 3;</code>
     */
    public int getActiveDays() {
      return activeDays_;
    }

    // optional int32 collectDays = 4;
    public static final int COLLECTDAYS_FIELD_NUMBER = 4;
    private int collectDays_;
    /**
     * <code>optional int32 collectDays = 4;</code>
     */
    public boolean hasCollectDays() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 collectDays = 4;</code>
     */
    public int getCollectDays() {
      return collectDays_;
    }

    private void initFields() {
      pkg_ = "";
      name_ = "";
      activeDays_ = 0;
      collectDays_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPkg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPkgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, activeDays_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, collectDays_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPkgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, activeDays_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, collectDays_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static App parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static App parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static App parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static App parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static App parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static App parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static App parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static App parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static App parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static App parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(App prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobf.App}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements AppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ComIflytekCtrPerson.internal_static_com_protobf_App_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ComIflytekCtrPerson.internal_static_com_protobf_App_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                App.class, Builder.class);
      }

      // Construct using com.protobf.ComIflytekCtrPerson.App.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pkg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        activeDays_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        collectDays_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ComIflytekCtrPerson.internal_static_com_protobf_App_descriptor;
      }

      public App getDefaultInstanceForType() {
        return App.getDefaultInstance();
      }

      public App build() {
        App result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public App buildPartial() {
        App result = new App(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pkg_ = pkg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.activeDays_ = activeDays_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.collectDays_ = collectDays_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof App) {
          return mergeFrom((App)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(App other) {
        if (other == App.getDefaultInstance()) return this;
        if (other.hasPkg()) {
          bitField0_ |= 0x00000001;
          pkg_ = other.pkg_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasActiveDays()) {
          setActiveDays(other.getActiveDays());
        }
        if (other.hasCollectDays()) {
          setCollectDays(other.getCollectDays());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPkg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        App parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (App) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string pkg = 1;
      private Object pkg_ = "";
      /**
       * <code>required string pkg = 1;</code>
       */
      public boolean hasPkg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string pkg = 1;</code>
       */
      public String getPkg() {
        Object ref = pkg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pkg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string pkg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPkgBytes() {
        Object ref = pkg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pkg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pkg = 1;</code>
       */
      public Builder setPkg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pkg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pkg = 1;</code>
       */
      public Builder clearPkg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pkg_ = getDefaultInstance().getPkg();
        onChanged();
        return this;
      }
      /**
       * <code>required string pkg = 1;</code>
       */
      public Builder setPkgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pkg_ = value;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 activeDays = 3;
      private int activeDays_ ;
      /**
       * <code>optional int32 activeDays = 3;</code>
       */
      public boolean hasActiveDays() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 activeDays = 3;</code>
       */
      public int getActiveDays() {
        return activeDays_;
      }
      /**
       * <code>optional int32 activeDays = 3;</code>
       */
      public Builder setActiveDays(int value) {
        bitField0_ |= 0x00000004;
        activeDays_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 activeDays = 3;</code>
       */
      public Builder clearActiveDays() {
        bitField0_ = (bitField0_ & ~0x00000004);
        activeDays_ = 0;
        onChanged();
        return this;
      }

      // optional int32 collectDays = 4;
      private int collectDays_ ;
      /**
       * <code>optional int32 collectDays = 4;</code>
       */
      public boolean hasCollectDays() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 collectDays = 4;</code>
       */
      public int getCollectDays() {
        return collectDays_;
      }
      /**
       * <code>optional int32 collectDays = 4;</code>
       */
      public Builder setCollectDays(int value) {
        bitField0_ |= 0x00000008;
        collectDays_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 collectDays = 4;</code>
       */
      public Builder clearCollectDays() {
        bitField0_ = (bitField0_ & ~0x00000008);
        collectDays_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.protobf.App)
    }

    static {
      defaultInstance = new App(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protobf.App)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobf_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protobf_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobf_App_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protobf_App_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034com.iflytek.ctr.person.proto\022\013com.prot" +
      "obf\"f\n\006Person\022\016\n\006acctID\030\001 \002(\003\022\016\n\006passwd\030" +
      "\002 \002(\t\022\r\n\005index\030\003 \003(\003\022\r\n\005value\030\004 \003(\003\022\036\n\004a" +
      "pps\030\005 \003(\0132\020.com.protobf.App\"I\n\003App\022\013\n\003pk" +
      "g\030\001 \002(\t\022\014\n\004name\030\002 \001(\t\022\022\n\nactiveDays\030\003 \001(" +
      "\005\022\023\n\013collectDays\030\004 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_protobf_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_protobf_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_protobf_Person_descriptor,
              new String[] { "AcctID", "Passwd", "Index", "Value", "Apps", });
          internal_static_com_protobf_App_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_protobf_App_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_protobf_App_descriptor,
              new String[] { "Pkg", "Name", "ActiveDays", "CollectDays", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
